config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :home
  resources :groups do
  resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :title , presence:true
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :group
validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
	@groups=Group.all
	end
	def new
		@group=Group.new
	end

	def show
		@group =Group.find(params[:id])
		@posts = @group.posts
	end
	def edit
		@group =Group.find(params[:id])
	end
	def create
		@group = Group.create(group_params)

		if @group.save
			redirect_to groups_path, notice: "新增討論板成功"
		else
			render :new
		end
	end
	def update
		@group = Group.find(params[:id])

		if @group.update(group_params)
			redirect_to groups_path, notice: "修改成功！"
		else
			render :edit
		end
	end
	def destroy
		@group=Group.find(params[:id])
		@group.destroy
		redirect_to groups_path,alert:"討論板已刪除"
	end

	private

	def group_params
		params.require(:group).permit(:title,:description)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_group
	def new
		@post = @group.posts.new
	end

	def create
		@post =@group.posts.build(post_params)

		if @post.save
			redirect_to group_path(@group), notice: "sucess"
		else
			render :new
		end
	end
	def edit
		@post = @group.posts.find(params[:id])
		
	end
	def update
		@post=@group.posts.find(params[:id])
		if @post.update(post_params)
		redirect_to group_path(@group), notice:"change sucess"
		else
		render :edit	
		end	
	end
	def destroy
		@post=@group.posts.find(params[:id])
		@post.destroy
		redirect_to group_path(@group), notice:"destroy succes"
	end
	#before_action
	def find_group
		@group= Group.find(params[:group_id])
	end
private
def post_params
	params.require(:post).permit(:content)
	
end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def notice_message
   alert_types = { notice: :success, alert: :danger }

   close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
   close_button = content_tag(:button, "×", close_button_options)

   alerts = flash.map do |type, message|
     alert_content = close_button + message

     alert_type = alert_types[type.to_sym] || type
     alert_class = "alert alert-#{alert_type} alert-dismissable"

     content_tag(:div, alert_content, class: alert_class)
   end

   alerts.join("\n").html_safe
 end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_footer.html.erb
<footer class="footerwrap">
				<h4>Created by <a href="https://www.facebook.com/profile.php?id=100005058070616">skywayoo</a> - Copyright 2016</h4>
				<div class="footer-icon" >
						<a href="https://twitter.com/skywayoo?lang=zh-tw">
							<div class="footer-icon-twitter"></div>
						</a>
						<a href="https://www.facebook.com/profile.php?id=100005058070616">
							<div class="footer-icon-facebook"></div>
						</a>
						<a href="https://github.com/skywayoo">
							<div class="footer-icon-git"></div>
						</a>
				</div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role = "navigation">
  <div class="container" id="nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                          <%= link_to root_path do %>
                          <%= image_tag "YZU.png" %>
                          <% end %>  
                </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">         
         <ul class="nav navbar-nav">
            <li> <%= link_to('lab首頁', root_path(:anchor => "home"), class: "smoothScroll")%></li>
            <!-- use :anchor to #id -->
            <li> <%= link_to('研究成員', root_path(:anchor => "memberwrap"), class: "smoothScroll")%></li>
            <li> <%= link_to('聯絡我們', root_path(:anchor => "contact"), class: "smoothScroll")%></li>
            <li> <%= link_to("討論區",groups_path)%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 Hi!, <%= current_user.name %>  
                 <b class="caret"></b>
              </a>
                <ul class="dropdown-menu">
                  <li> <%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
                  <li> <%= link_to('修改密碼', edit_registration_path(:user)) %></li>
                </ul>
            </li>
        <% else %>
            <%= link_to new_registration_path(:user)do%>
            <button class="btn btn-default navbar-btn">註冊</button><% end %>
            <%= link_to new_session_path(:user)do %> 
            <button class="btn btn-default navbar-btn">登入</button><% end %>
        <% end %>
          </ul>
        </div>
  </div>
</nav>

app/views/groups/edit.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4">
	<h1>修改討論版</h1>	
	<hr>

	<%= simple_form_for @group do |f| %>
	<div class="form-group">
		<%= f.input :title %>
		<%= f.input :description %>
	</div>
		<%= f.submit "送出",class: "btn btn-primary",data: { disable_with: "Submitting..."} %>
		<% end %>
 </div>
 </div>

app/views/groups/index.html.erb
<div class="container">
<div class="row">
<i class="fa fa-group fa-3x" style="padding:10px;"> 討論區</i>
<div class="col-md-12">
  <div class="group">
    <%= link_to("新增討論版", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>編號</td>
        <td>主題</td>
        <td>討論區簡介</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%=group.id%></td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
              <%= link_to("編輯", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("刪除", group_path(group),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "確認刪除?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
</div>

app/views/groups/new.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4">
  <h1>新增討論版</h1>
  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "送出", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>
</div>

app/views/groups/show.html.erb
<div class="container">
<div class="row">
  <div class="text-right">
    <%= link_to("新增文章",new_group_post_path(@group),class: "btn btn-warning")%>
    <%= link_to("編輯討論版", edit_group_path(@group), class: "btn btn-primary")%>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
  	<thead>
  		<tr>
  			<th>文章</th>
  			<th colspan="2" rowspan="" headers="" scope=""></th>
  		</tr>
  	</thead>
  	<tbody>
  		<% @posts.each do |post| %>
  		<tr>
  		<td><%= post.content %></td>
  		<td align="right"><%= link_to("編輯", edit_group_post_path(post.group,post),class:"btn btn-default btn-xs")%>
  		<%= link_to("刪除", group_post_path(post.group,post),class:"btn btn-default btn-xs",method: :delete,data:{confirm:"確認刪除?"})%>
  		</td>
  		</tr>
  		<% end %>
  	</tbody>
  </table>
</div>
</div>

app/views/home/index.html.erb
  	<div id="headwrap">
  	<div class="row centered" id="home">
		<div class="head-text">
			<h1><b>資訊管理學系</b></h1>
			<h1>決策分析與管理  研究室</h1>
			<h1>No<span data-typer-targets=" Pain., Gain."></span></h1>
		</div>
	</div>
	</div>
	<div class="">
		<div class="row"></div>
	</div>
	<div id="carouselwrap">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-example" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example" data-slide-to="1"></li>
				<li data-target="#carousel-example" data-slide-to="2"></li>
				<li data-target="#carousel-example" data-slide-to="3"></li>
			</ol>
			<!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <%= image_tag("slide1.jpg")%>
        <div class="carousel-caption">
          <h2>活動照片</h2>
          <p>畢業囉~~~~</p>
        </div>
      </div>

      <div class="item">
       	  <%= image_tag("slide2.jpg")%>
          <div class="carousel-caption">
          <h2>活動照片</h2>
          <p>畢業囉~~~~ </p>
        </div>
      </div>
    
      <div class="item">
        <%= image_tag("slide3.jpg")%>
        <div class="carousel-caption">
          <h2>活動照片</h2>
          <p>畢業囉~~~~</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag("slide4.jpg")%>
        <div class="carousel-caption">
          <h2>活動照片</h2>
          <p>畢業囉~~~~</p>
        </div>
      </div>

    <!-- Left and right controls -->
    	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      		<span class="sr-only">Previous</span>
    	</a>
    	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
     		<span class="sr-only">Next</span>
    	</a>
	</div>
	</div>
	</div>
	<div id="memberwrap">
	<div class="row" id="member">
			<h1 class="centered"><b>研究成員</b></h1>
			<hr>
		<div class="row centered" >
			<div class="col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1">
			<div class="wow fadeInDown" data-wow-duration="800ms" data-wow-delay="500ms">
				<%= image_tag("teacher.jpg" , class: "img-circle boss")%>		
				<h2><b>許嘉裕</b></h2>				
			</div>
			</div>
			<div class="col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-2">
				<div class="wow fadeInDown" data-wow-duration="800ms" data-wow-delay="700ms">
					<h2>Chia-Yu Hsu</h2>
					<h2>副教授</h2>
					<br>
					<br>
					<p class="info"><font size="5">電話: (03) 463-8800 分機 2793</font></p>
					<p class="info"><font size="5">傳真: (03) 463-2077</font></p>
					<p class="info"><font size="5">辦公地址: 六館七樓 R60704</font></p>
					<p class="info"><font size="5">E-Mail: cyhsu@saturn.yzu.edu.tw</font></p>
				</div>
			</div>
		</div>
	<hr>
		<div class="row-fluid centered">
			<div class="member col-md-4 col-sm-6">
				<div class="wow flipInX" data-wow-delay="100ms"><%= image_tag("boss4.jpg", class: "img-circle student")%>
				<h2>鍾世恩</h2></div>
					<a href="#"> <%= image_tag("icon/twitter.png", class: "icon") %></a>
					<a href="https://www.facebook.com/shihen.jhong?fref=ts"> <%= image_tag("icon/facebook.png", class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png", class: "icon") %></a>		
			</div>
			<div class="member col-md-4 col-sm-6 ">
				<div class="wow flipInX" data-wow-delay="300ms"><%= image_tag("boss2.jpg", class: "img-circle student")%>
				<h2>陳名彥</h2></div>
					<a href="#"> <%= image_tag("icon/twitter.png", class: "icon") %></a>
					<a href="https://www.facebook.com/profile.php?id=100001304190729&fref=ts"> <%= image_tag("icon/facebook.png", class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png", class: "icon") %></a>	
			</div>
			<div class="member col-md-4 col-sm-6">
				<div class="wow flipInX" data-wow-delay="500ms"><%= image_tag("boss3.jpg", class: "img-circle student")%>
				<h2>林見遠</h2></div>
					<a href="#"> <%= image_tag("icon/twitter.png", class: "icon") %></a>
					<a href="https://www.facebook.com/chienyuan.lin.9?fref=ts"> <%= image_tag("icon/facebook.png", class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png", class: "icon") %></a>	
			</div>
		</div>

		<div class="row-fluid centered">
			<div class="member col-md-4 col-sm-6">
				<div class="wow flipInX" data-wow-delay="600ms"><%= image_tag("boss1.jpg", class: "img-circle student")%>
				<h2>劉韋辰</h2></div>
					<a href="#"><%= image_tag("icon/twitter.png" , class: "icon") %></a>
					<a href="https://www.facebook.com/profile.php?id=100005058070616"> <%= image_tag("icon/facebook.png" , class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png" , class: "icon") %></a>		
			</div>
			<div class="member col-md-4 col-sm-6">
				<div class="wow flipInX" data-wow-delay="800ms"><%= image_tag("boss5.jpg", class: "img-circle student")%>
				<h2>林子皓</h2></div>
					<a href="#"> <%= image_tag("icon/twitter.png" , class: "icon") %></a>
					<a href="https://www.facebook.com/hao.lin.52?fref=ufi"> <%= image_tag("icon/facebook.png" , class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png" , class: "icon") %></a>	
			</div>
			<div class="member col-md-4 col-sm-6">
				<div class="wow flipInX" data-wow-delay="1000ms"><%= image_tag("boss1.jpg", class: "img-circle student")%>
				<h2>xxx</h2></div>
					<a href="#"> <%= image_tag("icon/twitter.png" , class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/facebook.png" , class: "icon") %></a>
					<a href="#"> <%= image_tag("icon/google.png" , class: "icon") %></a>	
			</div>
		</div>
	</div>
	</div>
	<div class="row centered" id="mediawrap">
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="media wow bounceInLeft" data-wow-delay="100ms"><i class="fa fa-group fa-5x"></i></div>
			<span class="counter"><%=User.count(:id)+123%></span>
			<span class="counter-title">會員用戶</span>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="media wow bounceInDown" data-wow-delay="500ms"><i class="fa fa-comments-o fa-5x"></i></div>
			<span class="counter"><%= Group.count(:id)+45%></span>
			<span class="counter-title">討論區主題</span>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="media wow bounceInRight" data-wow-delay="900ms"><i class="fa fa-thumbs-o-up fa-5x"></i></div>
			<span class="counter" id="fblike"></span>
			<span class="counter-title">粉絲團按讚數</span>
		</div>
	</div>
	<!-- ==== GREYWRAP ==== -->
		<div id="greywrap">
				<div class="row" id="contact">
					<div class="col-md-7 centered col-sm-7">
						<div class="info wow slideInLeft" data-wow-duration="800ms" data-wow-delay="800ms">
							<%= image_tag("macbook.png", class: "image")%>
						</div>
					</div>
					<div class="col-md-5 col-sm-5">
						<div class="wow fadeInDown" data-wow-duration="800ms" data-wow-delay="1200ms" >
							<h1 align="center">聯絡資訊</h1>
							<br>
							<p class="info"><%= image_tag("icon/mail.png", class: "icon")%><font size="5"> 　lab1609@gmail.com</font></p>
							<p class="info"><%= image_tag("icon/location.png", class: "icon")%><font size="5"> 　資訊學院一館六樓 1609實驗室 </font></p>
							<p class="info"><%= image_tag("icon/call.png", class: "icon")%><font size="5"> 　(03)4638800,分機1609</font></p>
							<a href="https://www.facebook.com/%E5%85%83%E6%99%BA%E5%A4%A7%E5%AD%B8%E8%B3%87%E8%A8%8A%E7%AE%A1%E7%90%86%E5%AD%B8%E7%B3%BBYuan-Ze-University-Information-Management-1676425955944996/?fref=ts" class="btn btn-success btn-lg">聯絡我們</a>
						</div>			
					</div>
				</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>study rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "common/navbar" %>	
		<div class="mainrow">
			<%= notice_message %>
			<%= yield%>
		</div>
	<%= render "common/footer" %>
<%= javascript_include_tag 'ws'%>
<%= javascript_include_tag 'smoothscroll'%>
<%= javascript_include_tag 'jquery.counterup'%>
<%= javascript_include_tag 'jquery.typer.min'%>
<%= javascript_include_tag 'wow'%>
<%= javascript_include_tag 'like'%>
<%= javascript_include_tag 'type'%>
</body>
</html>

app/views/posts/edit.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4">
	<h1>修改文章</h1>	
	<hr>

	<%= simple_form_for [@group,@post] do |f| %>
	<div class="form-group">
		<%= f.input :content %>
	</div>
		<%= f.submit "送出",class: "btn btn-primary",data: { disable_with: "正在送出..."} %>
		<% end %>
 </div>
 </div>

app/views/posts/new.html.erb
<div class="row">
  <h1 class="text-center">新增文章</h1>
<div class="col-md-4 col-md-offset-4">
  <hr>
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "送出", data: { disable_with: "正在送出..." },class: "btn btn-primary pull-center" %>
  <% end %>
</div>
</div>